---
- name: create accounts for users
  user:
    name: "{{item.name}}"
    groups: "{{user_groups}}"
    append: no
    shell: "{{shell}}"
    state: present
  with_items: users

- name: create accounts for non-sudo users
  user:
    name: "{{item.name}}"
    groups: "{{nosudo_groups}}"
    append: no
    shell: /bin/bash
    state: present
  with_items: nosudo_users

- name: add keys to sudo accounts
  authorized_key:
    user: "{{item.0.name}}"
    key: "{{item.1}}"
    exclusive: yes
  with_subelements:
    - sudo_users
    - authorized

- name: add keys to nosudo accounts
  authorized_key:
    user: "{{item.0.name}}"
    key: "{{item.1}}"
    exclusive: yes
  with_subelements:
    - nosudo_users
    - authorized
